/**
 * This code was autogenerated from a Postman source
 */
const http = require('http');
const PORT = process.env.PORT || 4500;

const server = http.createServer((req, res) => {
  const url = new URL(req.url || '', 'http://localhost');
  const pathname = url.pathname;

  // @endpoint POST /auth/login
  if (req.method === 'POST' && pathname === '/auth/login') {
    const requestedStatusCode = req.headers['x-mock-response-code'];

    // "401 Invalid Credentials" — when x-mock-response-code: 401
    if (requestedStatusCode === '401') {
      res.writeHead(401, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"error":"invalid_credentials","message":"Email or password is incorrect."}));
    }

    // "200 OK" — default
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c3ItMDAxIiwiZW1haWwiOiJhbGljZUBub3J0aGJlYW0uY29tIiwicm9sZSI6ImVtcGxveWVlIiwiaWF0IjoxNzAwMDAwMDAwLCJleHAiOjE3MDAwMDM2MDB9.signature","user":{"id":"usr-001","email":"alice@northbeam.com","name":"Alice Chen","role":"employee"}}));
  }

  // @endpoint POST /auth/login
  if (req.method === 'POST' && pathname === '/auth/login') {
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c3ItMDAyIiwiZW1haWwiOiJib2JAbm9ydGhiZWFtLmNvbSIsInJvbGUiOiJhcHByb3ZlciIsImlhdCI6MTcwMDAwMDAwMCwiZXhwIjoxNzAwMDAzNjAwfQ.signature","user":{"id":"usr-002","email":"bob@northbeam.com","name":"Bob Martinez","role":"approver"}}));
  }

  // @endpoint POST /auth/login
  if (req.method === 'POST' && pathname === '/auth/login') {
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c3ItMDAzIiwiZW1haWwiOiJjYXJvbEBub3J0aGJlYW0uY29tIiwicm9sZSI6ImZpbmFuY2UiLCJpYXQiOjE3MDAwMDAwMDAsImV4cCI6MTcwMDAwMzYwMH0.signature","user":{"id":"usr-003","email":"carol@northbeam.com","name":"Carol Singh","role":"finance"}}));
  }

  // @endpoint GET /categories
  if (req.method === 'GET' && pathname === '/categories') {
    const requestedStatusCode = req.headers['x-mock-response-code'];

    // "401 Unauthorized" — when x-mock-response-code: 401
    if (requestedStatusCode === '401') {
      res.writeHead(401, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"error":"unauthorized","message":"A valid Bearer token is required."}));
    }

    // "200 OK" — default
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"categories":[{"id":"cat-001","name":"Travel","description":"Flights, trains, taxis and other transport","receipt_threshold":50,"currency":"USD","created_at":"2024-01-01T00:00:00Z","updated_at":"2024-01-01T00:00:00Z"},{"id":"cat-002","name":"Meals & Entertainment","description":"Business meals and client entertainment","receipt_threshold":25,"currency":"USD","created_at":"2024-01-01T00:00:00Z","updated_at":"2024-01-01T00:00:00Z"},{"id":"cat-003","name":"Accommodation","description":"Hotels and other lodging","receipt_threshold":100,"currency":"USD","created_at":"2024-01-01T00:00:00Z","updated_at":"2024-01-01T00:00:00Z"},{"id":"cat-004","name":"Office Supplies","description":"Stationery, equipment and other office items","receipt_threshold":30,"currency":"USD","created_at":"2024-01-01T00:00:00Z","updated_at":"2024-01-01T00:00:00Z"}],"total":4}));
  }

  // @endpoint GET /categories/:categoryId
  if (req.method === 'GET' && /^\/categories\/([^/]+)$/.test(pathname)) {
    const requestedStatusCode = req.headers['x-mock-response-code'];

    // "404 Not Found" — when x-mock-response-code: 404
    if (requestedStatusCode === '404') {
      res.writeHead(404, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"error":"not_found","message":"Category cat-999 does not exist."}));
    }

    // "200 OK" — default
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"id":"cat-001","name":"Travel","description":"Flights, trains, taxis and other transport","receipt_threshold":50,"currency":"USD","created_at":"2024-01-01T00:00:00Z","updated_at":"2024-01-01T00:00:00Z"}));
  }

  // @endpoint POST /categories
  if (req.method === 'POST' && pathname === '/categories') {
    const requestedStatusCode = req.headers['x-mock-response-code'];

    // "403 Forbidden" — when x-mock-response-code: 403
    if (requestedStatusCode === '403') {
      res.writeHead(403, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"error":"forbidden","message":"Only Finance users may create categories."}));
    }

    // "422 Validation Error" — when x-mock-response-code: 422
    if (requestedStatusCode === '422') {
      res.writeHead(422, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"error":"validation_error","message":"Request body contains invalid fields.","details":[{"field":"name","issue":"name is required and cannot be empty."},{"field":"receipt_threshold","issue":"receipt_threshold must be a positive number."}]}));
    }

    // "201 Created" — default
    res.writeHead(201, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"id":"cat-005","name":"Software & Subscriptions","description":"SaaS tools, licenses and software subscriptions","receipt_threshold":20,"currency":"USD","created_at":"2024-06-01T10:00:00Z","updated_at":"2024-06-01T10:00:00Z"}));
  }

  // @endpoint PUT /categories/:categoryId
  if (req.method === 'PUT' && /^\/categories\/([^/]+)$/.test(pathname)) {
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"id":"cat-001","name":"Travel & Transport","description":"Flights, trains, taxis, car hire and other transport","receipt_threshold":75,"currency":"USD","created_at":"2024-01-01T00:00:00Z","updated_at":"2024-06-15T09:30:00Z"}));
  }

  // @endpoint DELETE /categories/:categoryId
  if (req.method === 'DELETE' && /^\/categories\/([^/]+)$/.test(pathname)) {
    const requestedStatusCode = req.headers['x-mock-response-code'];

    // "403 Forbidden" — when x-mock-response-code: 403
    if (requestedStatusCode === '403') {
      res.writeHead(403, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"error":"forbidden","message":"Only Finance users may delete categories."}));
    }

    // "204 No Content" — default
    res.writeHead(204, {"Content-Type":"text/plain"});
    return res.end("");
  }

  // @endpoint GET /expenses
  if (req.method === 'GET' && pathname === '/expenses') {
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"expenses":[{"id":"exp-001","employee_id":"usr-001","category_id":"cat-001","category_name":"Travel","amount":120.5,"currency":"USD","date":"2024-06-10","merchant":"Delta Airlines","description":"Flight to NYC for client meeting","receipt_url":"https://storage.northbeam.com/receipts/exp-001.pdf","status":"unclaimed","claim_id":null,"created_at":"2024-06-10T18:00:00Z","updated_at":"2024-06-10T18:00:00Z"},{"id":"exp-002","employee_id":"usr-001","category_id":"cat-002","category_name":"Meals & Entertainment","amount":18.75,"currency":"USD","date":"2024-06-11","merchant":"The Capital Grille","description":"Lunch with client","receipt_url":null,"status":"unclaimed","claim_id":null,"created_at":"2024-06-11T14:30:00Z","updated_at":"2024-06-11T14:30:00Z"}],"total":2}));
  }

  // @endpoint GET /expenses/:expenseId
  if (req.method === 'GET' && /^\/expenses\/([^/]+)$/.test(pathname)) {
    const requestedStatusCode = req.headers['x-mock-response-code'];

    // "404 Not Found" — when x-mock-response-code: 404
    if (requestedStatusCode === '404') {
      res.writeHead(404, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"error":"not_found","message":"Expense exp-999 does not exist."}));
    }

    // "200 OK" — default
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"id":"exp-001","employee_id":"usr-001","category_id":"cat-001","category_name":"Travel","amount":120.5,"currency":"USD","date":"2024-06-10","merchant":"Delta Airlines","description":"Flight to NYC for client meeting","receipt_url":"https://storage.northbeam.com/receipts/exp-001.pdf","status":"unclaimed","claim_id":null,"created_at":"2024-06-10T18:00:00Z","updated_at":"2024-06-10T18:00:00Z"}));
  }

  // @endpoint POST /expenses
  if (req.method === 'POST' && pathname === '/expenses') {
    const requestedStatusCode = req.headers['x-mock-response-code'];

    // "422 Future Date" — when x-mock-response-code: 422
    if (requestedStatusCode === '422') {
      res.writeHead(422, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"error":"validation_error","message":"Request body contains invalid fields.","details":[{"field":"date","issue":"Expense date cannot be in the future."}]}));
    }

    // "201 Created" — default
    res.writeHead(201, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"id":"exp-001","employee_id":"usr-001","category_id":"cat-001","category_name":"Travel","amount":120.5,"currency":"USD","date":"2024-06-10","merchant":"Delta Airlines","description":"Flight to NYC for client meeting","receipt_url":"https://storage.northbeam.com/receipts/exp-001.pdf","status":"unclaimed","claim_id":null,"created_at":"2024-06-10T18:00:00Z","updated_at":"2024-06-10T18:00:00Z"}));
  }

  // @endpoint PUT /expenses/:expenseId
  if (req.method === 'PUT' && /^\/expenses\/([^/]+)$/.test(pathname)) {
    const requestedStatusCode = req.headers['x-mock-response-code'];

    // "409 Expense Frozen" — when x-mock-response-code: 409
    if (requestedStatusCode === '409') {
      res.writeHead(409, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"error":"expense_frozen","message":"Expense exp-003 is part of a submitted claim and cannot be modified."}));
    }

    // "200 OK" — default
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"id":"exp-001","employee_id":"usr-001","category_id":"cat-001","category_name":"Travel","amount":135,"currency":"USD","date":"2024-06-10","merchant":"Delta Airlines","description":"Flight to NYC for client meeting (updated fare)","receipt_url":"https://storage.northbeam.com/receipts/exp-001-v2.pdf","status":"unclaimed","claim_id":null,"created_at":"2024-06-10T18:00:00Z","updated_at":"2024-06-15T10:00:00Z"}));
  }

  // @endpoint DELETE /expenses/:expenseId
  if (req.method === 'DELETE' && /^\/expenses\/([^/]+)$/.test(pathname)) {
    const requestedStatusCode = req.headers['x-mock-response-code'];

    // "409 Expense Frozen" — when x-mock-response-code: 409
    if (requestedStatusCode === '409') {
      res.writeHead(409, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"error":"expense_frozen","message":"Expense exp-003 is part of a submitted claim and cannot be deleted."}));
    }

    // "204 No Content" — default
    res.writeHead(204, {"Content-Type":"text/plain"});
    return res.end("");
  }

  // @endpoint GET /claims
  if (req.method === 'GET' && pathname === '/claims') {
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"claims":[{"id":"clm-001","employee_id":"usr-001","employee_name":"Alice Chen","title":"June 2024 NYC Trip","status":"submitted","total_amount":139.25,"currency":"USD","expense_count":2,"submitted_at":"2024-06-12T09:00:00Z","created_at":"2024-06-11T20:00:00Z","updated_at":"2024-06-12T09:00:00Z"},{"id":"clm-002","employee_id":"usr-001","employee_name":"Alice Chen","title":"May 2024 Expenses","status":"reimbursed","total_amount":245,"currency":"USD","expense_count":3,"submitted_at":"2024-05-31T17:00:00Z","created_at":"2024-05-30T10:00:00Z","updated_at":"2024-06-05T11:00:00Z"}],"total":2}));
  }

  // @endpoint GET /claims/:claimId
  if (req.method === 'GET' && /^\/claims\/([^/]+)$/.test(pathname)) {
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"id":"clm-001","employee_id":"usr-001","employee_name":"Alice Chen","title":"June 2024 NYC Trip","status":"submitted","total_amount":139.25,"currency":"USD","submitted_at":"2024-06-12T09:00:00Z","created_at":"2024-06-11T20:00:00Z","updated_at":"2024-06-12T09:00:00Z","expenses":[{"id":"exp-001","category_name":"Travel","amount":120.5,"currency":"USD","date":"2024-06-10","merchant":"Delta Airlines","description":"Flight to NYC for client meeting"},{"id":"exp-002","category_name":"Meals & Entertainment","amount":18.75,"currency":"USD","date":"2024-06-11","merchant":"The Capital Grille","description":"Lunch with client"}]}));
  }

  // @endpoint POST /claims
  if (req.method === 'POST' && pathname === '/claims') {
    const requestedStatusCode = req.headers['x-mock-response-code'];

    // "422 Already Claimed" — when x-mock-response-code: 422
    if (requestedStatusCode === '422') {
      res.writeHead(422, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"error":"validation_error","message":"One or more expenses cannot be added to a claim.","details":[{"expense_id":"exp-003","issue":"Expense exp-003 is already part of claim clm-002."}]}));
    }

    // "201 Created" — default
    res.writeHead(201, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"id":"clm-001","employee_id":"usr-001","employee_name":"Alice Chen","title":"June 2024 NYC Trip","status":"draft","total_amount":139.25,"currency":"USD","expense_count":2,"submitted_at":null,"created_at":"2024-06-11T20:00:00Z","updated_at":"2024-06-11T20:00:00Z"}));
  }

  // @endpoint POST /claims/:claimId/submit
  if (req.method === 'POST' && /^\/claims\/([^/]+)\/submit$/.test(pathname)) {
    const requestedStatusCode = req.headers['x-mock-response-code'];

    // "409 Invalid State Transition" — when x-mock-response-code: 409
    if (requestedStatusCode === '409') {
      res.writeHead(409, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"error":"invalid_state_transition","message":"Claim clm-001 is already submitted and cannot be submitted again.","current_status":"submitted"}));
    }

    // "200 OK" — default
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"id":"clm-001","employee_id":"usr-001","employee_name":"Alice Chen","title":"June 2024 NYC Trip","status":"submitted","total_amount":139.25,"currency":"USD","expense_count":2,"submitted_at":"2024-06-12T09:00:00Z","created_at":"2024-06-11T20:00:00Z","updated_at":"2024-06-12T09:00:00Z"}));
  }

  // @endpoint POST /claims/:claimId/approve
  if (req.method === 'POST' && /^\/claims\/([^/]+)\/approve$/.test(pathname)) {
    const requestedStatusCode = req.headers['x-mock-response-code'];

    // "403 Cannot Approve Own Claim" — when x-mock-response-code: 403
    if (requestedStatusCode === '403') {
      res.writeHead(403, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"error":"forbidden","message":"An approver cannot approve their own claim."}));
    }

    // "409 Not Submitted" — when x-mock-response-code: 409
    if (requestedStatusCode === '409') {
      res.writeHead(409, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"error":"invalid_state_transition","message":"Only submitted claims can be approved. Claim clm-004 is in draft status.","current_status":"draft"}));
    }

    // "200 OK" — default
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"id":"clm-001","employee_id":"usr-001","employee_name":"Alice Chen","title":"June 2024 NYC Trip","status":"approved","total_amount":139.25,"currency":"USD","expense_count":2,"approved_by":"usr-002","approved_at":"2024-06-13T10:30:00Z","submitted_at":"2024-06-12T09:00:00Z","created_at":"2024-06-11T20:00:00Z","updated_at":"2024-06-13T10:30:00Z"}));
  }

  res.writeHead(404, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({ error: 'Endpoint not defined' }));
});

server.listen(PORT);
